### PR TITLE
Bug/17025 solutions overlapping text

### PR DESCRIPTION
**Pull request by gm3197**
* Fix overlapping text

### CODE REVIEW

**Comment by michaeljwiebe** [comment]
thats not going to work. this is below 1200px
Screen Shot 2022-06-28 at 5 12 12 PM

**Review by michaeljwiebe — CHANGES_REQUESTED** [review]
super concise, thats great. however it doesn't work below 1200px

**Comment by gm3197** [comment]
> thats not going to work. this is below 1200px Screen Shot 2022-06-28 at 5 12 12 PM

Actually a completely unrelated issue. I was using the browser devtools responsive design mode to test it at different sizes and that simulates the physical screen actually changing sizes (`window.screen.width`), but normally resizing a browser window on a non mobile device only changes `window.innerWidth` since the size of your display cannot change. Should be fixed now.

**Review by michaeljwiebe — APPROVED** [review]

**Comment by michaeljwiebe** [comment]
merging this bc the live site has this problem as well

**Pull request merged**
